### ISSUE TITLE
View Click Points

### ISSUE THREAD

**Issue by furkanssk** [FierceThundr/wttg2-assistant#24]
Hey! Ur WTTG 2 assistant is incredible, but i have a question.
Some of the places where you show the click points are yellow, some are green and some are red?
What do these colors mean?
Thx for ur answer.

**Comment by FierceThundr** [comment]
The colored outlines show information about zones that have to do with either where you may need to click to receive a key or where keys can be visibly placed on a page. Keep in mind only one clickpoint will be active at a time and that is assuming the key is not hidden in the source code or immediately visible on the page.

Yellow outlines are clickpoints that will place a key somewhere on the current page. 
Green outlines are clickpoints that will place a key in a file on your in game desktop.
Cyan outlines are clickpoints that can function as either yellow or green above.
Red outlines are locations keys can be placed on a page when loaded or by clicking a yellow clickpoint.

**Comment by FierceThundr** [comment]
Feel free to ask any more questions if you have them
